spring:
  security:
    user:
      name: user
      password: user

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      authorized-grant-types: authorization_code, refresh_token, password
      scope: openid
      
   